/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import {
  Loan,
  LoanInstance,
  LendingMarketplace,
  LendingMarketplaceInstance,
  Oracle,
  OracleInstance,
} from ".";
import { default as testnetDeployments } from "../.deployments.testnet.json";
import { default as devnetDeployments } from "../.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    Loan: DeployContractExecutionResult<LoanInstance>;
    LendingMarketplace: DeployContractExecutionResult<LendingMarketplaceInstance>;
    Oracle?: DeployContractExecutionResult<OracleInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    Loan: {
      ...json.contracts["Loan"],
      contractInstance: Loan.at(
        json.contracts["Loan"].contractInstance.address
      ),
    },
    LendingMarketplace: {
      ...json.contracts["LendingMarketplace"],
      contractInstance: LendingMarketplace.at(
        json.contracts["LendingMarketplace"].contractInstance.address
      ),
    },
    Oracle:
      json.contracts["Oracle"] === undefined
        ? undefined
        : {
            ...json.contracts["Oracle"],
            contractInstance: Oracle.at(
              json.contracts["Oracle"].contractInstance.address
            ),
          },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
