/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as LendingMarketplaceContractJson } from "../LendingMarketplace.ral.json";
import { getContractByCodeHash } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace LendingMarketplaceTypes {
  export type Fields = {
    loanTemplateId: HexString;
    admin: Address;
    totalLoans: bigint;
    feeRate: bigint;
    lendingEnabled: boolean;
  };

  export type State = ContractState<Fields>;

  export type AdminUpdatedEvent = ContractEvent<{
    previous: Address;
    new: Address;
  }>;
  export type LoanDetailsEvent = ContractEvent<{
    loanId: HexString;
    lendingTokenId: HexString;
    collateralTokenId: HexString;
    lendingAmount: bigint;
    collateralAmount: bigint;
    interestRate: bigint;
    duration: bigint;
    lender: Address;
  }>;
  export type LoanCreatedEvent = ContractEvent<{
    loanId: HexString;
    id: bigint;
    by: Address;
    timestamp: bigint;
  }>;
  export type LoanCancelledEvent = ContractEvent<{
    loanId: HexString;
    by: Address;
    timestamp: bigint;
  }>;
  export type LoanPaidEvent = ContractEvent<{
    loanId: HexString;
    by: Address;
    timestamp: bigint;
  }>;
  export type LoanAcceptedEvent = ContractEvent<{
    loanId: HexString;
    by: Address;
    timestamp: bigint;
  }>;
  export type LoanLiquidatedEvent = ContractEvent<{
    loanId: HexString;
    by: Address;
    timestamp: bigint;
  }>;

  export interface CallMethodTable {
    blockTimeStampInSeconds: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    calculateInterestPayment: {
      params: CallContractParams<{
        currentBlockTimeStamp: bigint;
        loanTimestamp: bigint;
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    calculateTotalInterestPayment: {
      params: CallContractParams<{
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    calculateMarketplaceFee: {
      params: CallContractParams<{ amount: bigint; feeRateValue: bigint }>;
      result: CallContractResult<bigint>;
    };
    getAdmin: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getTotalLoans: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getFeeRate: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    createLoan: {
      params: CallContractParams<{
        lendingTokenId: HexString;
        collateralTokenId: HexString;
        lendingAmount: bigint;
        collateralAmount: bigint;
        interestRate: bigint;
        duration: bigint;
      }>;
      result: CallContractResult<Address>;
    };
    borrow: {
      params: CallContractParams<{ loanId: HexString }>;
      result: CallContractResult<null>;
    };
    cancelLoan: {
      params: CallContractParams<{ loanId: HexString }>;
      result: CallContractResult<null>;
    };
    repayLoan: {
      params: CallContractParams<{ loanId: HexString }>;
      result: CallContractResult<null>;
    };
    liquidateLoan: {
      params: CallContractParams<{ loanId: HexString }>;
      result: CallContractResult<null>;
    };
    updateAdmin: {
      params: CallContractParams<{ newAdmin: Address }>;
      result: CallContractResult<null>;
    };
    updateFeeRate: {
      params: CallContractParams<{ value: bigint }>;
      result: CallContractResult<null>;
    };
    pauseLending: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    enableLending: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{
        to: Address;
        tokenId: HexString;
        amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    deposit: {
      params: CallContractParams<{ tokenId: HexString; amount: bigint }>;
      result: CallContractResult<null>;
    };
    addFeeToken: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<null>;
    };
    removeFeeToken: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<null>;
    };
    isFeeToken: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<boolean>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    blockTimeStampInSeconds: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    calculateInterestPayment: {
      params: SignExecuteContractMethodParams<{
        currentBlockTimeStamp: bigint;
        loanTimestamp: bigint;
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateTotalInterestPayment: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateMarketplaceFee: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        feeRateValue: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getAdmin: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalLoans: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getFeeRate: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    createLoan: {
      params: SignExecuteContractMethodParams<{
        lendingTokenId: HexString;
        collateralTokenId: HexString;
        lendingAmount: bigint;
        collateralAmount: bigint;
        interestRate: bigint;
        duration: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    borrow: {
      params: SignExecuteContractMethodParams<{ loanId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    cancelLoan: {
      params: SignExecuteContractMethodParams<{ loanId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    repayLoan: {
      params: SignExecuteContractMethodParams<{ loanId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    liquidateLoan: {
      params: SignExecuteContractMethodParams<{ loanId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updateAdmin: {
      params: SignExecuteContractMethodParams<{ newAdmin: Address }>;
      result: SignExecuteScriptTxResult;
    };
    updateFeeRate: {
      params: SignExecuteContractMethodParams<{ value: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    pauseLending: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    enableLending: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{
        to: Address;
        tokenId: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{
        tokenId: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    addFeeToken: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    removeFeeToken: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    isFeeToken: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  LendingMarketplaceInstance,
  LendingMarketplaceTypes.Fields
> {
  encodeFields(fields: LendingMarketplaceTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as LendingMarketplaceTypes.Fields;
  }

  eventIndex = {
    AdminUpdated: 0,
    LoanDetails: 1,
    LoanCreated: 2,
    LoanCancelled: 3,
    LoanPaid: 4,
    LoanAccepted: 5,
    LoanLiquidated: 6,
  };
  consts = {
    Day: BigInt("86400"),
    ErrorCodes: {
      AdminAllowedOnly: BigInt("0"),
      LendingDisabled: BigInt("1"),
      LenderAllowedOnly: BigInt("2"),
      BorrowerAllowedOnly: BigInt("3"),
      LenderNotAllowed: BigInt("4"),
      InvalidLendingAmount: BigInt("5"),
      InvalidCollateralAmount: BigInt("6"),
      InvalidInterestRate: BigInt("7"),
      InvalidDuration: BigInt("8"),
    },
  };

  at(address: string): LendingMarketplaceInstance {
    return new LendingMarketplaceInstance(address);
  }

  tests = {
    blockTimeStampInSeconds: async (
      params: Omit<
        TestContractParams<
          LendingMarketplaceTypes.Fields,
          never,
          { feeTokens?: Map<HexString, boolean> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<bigint, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(
        this,
        "blockTimeStampInSeconds",
        params,
        getContractByCodeHash
      );
    },
    calculateInterestPayment: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        {
          currentBlockTimeStamp: bigint;
          loanTimestamp: bigint;
          amount: bigint;
          interest: bigint;
          days: bigint;
        },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<bigint, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(
        this,
        "calculateInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateTotalInterestPayment: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { amount: bigint; interest: bigint; days: bigint },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<bigint, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(
        this,
        "calculateTotalInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateMarketplaceFee: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { amount: bigint; feeRateValue: bigint },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<bigint, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(
        this,
        "calculateMarketplaceFee",
        params,
        getContractByCodeHash
      );
    },
    getAdmin: async (
      params: Omit<
        TestContractParams<
          LendingMarketplaceTypes.Fields,
          never,
          { feeTokens?: Map<HexString, boolean> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<Address, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "getAdmin", params, getContractByCodeHash);
    },
    getTotalLoans: async (
      params: Omit<
        TestContractParams<
          LendingMarketplaceTypes.Fields,
          never,
          { feeTokens?: Map<HexString, boolean> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<bigint, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "getTotalLoans", params, getContractByCodeHash);
    },
    getFeeRate: async (
      params: Omit<
        TestContractParams<
          LendingMarketplaceTypes.Fields,
          never,
          { feeTokens?: Map<HexString, boolean> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<bigint, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "getFeeRate", params, getContractByCodeHash);
    },
    createLoan: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        {
          lendingTokenId: HexString;
          collateralTokenId: HexString;
          lendingAmount: bigint;
          collateralAmount: bigint;
          interestRate: bigint;
          duration: bigint;
        },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<Address, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "createLoan", params, getContractByCodeHash);
    },
    borrow: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { loanId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "borrow", params, getContractByCodeHash);
    },
    cancelLoan: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { loanId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "cancelLoan", params, getContractByCodeHash);
    },
    repayLoan: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { loanId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "repayLoan", params, getContractByCodeHash);
    },
    liquidateLoan: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { loanId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "liquidateLoan", params, getContractByCodeHash);
    },
    updateAdmin: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { newAdmin: Address },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "updateAdmin", params, getContractByCodeHash);
    },
    updateFeeRate: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { value: bigint },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "updateFeeRate", params, getContractByCodeHash);
    },
    pauseLending: async (
      params: Omit<
        TestContractParams<
          LendingMarketplaceTypes.Fields,
          never,
          { feeTokens?: Map<HexString, boolean> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "pauseLending", params, getContractByCodeHash);
    },
    enableLending: async (
      params: Omit<
        TestContractParams<
          LendingMarketplaceTypes.Fields,
          never,
          { feeTokens?: Map<HexString, boolean> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "enableLending", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { to: Address; tokenId: HexString; amount: bigint },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    deposit: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { tokenId: HexString; amount: bigint },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    addFeeToken: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { tokenId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "addFeeToken", params, getContractByCodeHash);
    },
    removeFeeToken: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { tokenId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<null, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "removeFeeToken", params, getContractByCodeHash);
    },
    isFeeToken: async (
      params: TestContractParams<
        LendingMarketplaceTypes.Fields,
        { tokenId: HexString },
        { feeTokens?: Map<HexString, boolean> }
      >
    ): Promise<
      TestContractResult<boolean, { feeTokens?: Map<HexString, boolean> }>
    > => {
      return testMethod(this, "isFeeToken", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const LendingMarketplace = new Factory(
  Contract.fromJson(
    LendingMarketplaceContractJson,
    "=76-1=1+8=2-2+37=2-2+54=1400-2+11=58+7a7e0214696e73657274206174206d617020706174683a2000=20+1=1-1=58+7a7e021472656d6f7665206174206d617020706174683a2000=64",
    "788c3cd69762b5096bb23d6258f1154af6882cb38d9ff0057fad173cf204bb09",
    []
  )
);

// Use this class to interact with the blockchain
export class LendingMarketplaceInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    feeTokens: new RalphMap<HexString, boolean>(
      LendingMarketplace.contract,
      this.contractId,
      "feeTokens"
    ),
  };

  async fetchState(): Promise<LendingMarketplaceTypes.State> {
    return fetchContractState(LendingMarketplace, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeAdminUpdatedEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.AdminUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "AdminUpdated",
      fromCount
    );
  }

  subscribeLoanDetailsEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.LoanDetailsEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "LoanDetails",
      fromCount
    );
  }

  subscribeLoanCreatedEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.LoanCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "LoanCreated",
      fromCount
    );
  }

  subscribeLoanCancelledEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.LoanCancelledEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "LoanCancelled",
      fromCount
    );
  }

  subscribeLoanPaidEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.LoanPaidEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "LoanPaid",
      fromCount
    );
  }

  subscribeLoanAcceptedEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.LoanAcceptedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "LoanAccepted",
      fromCount
    );
  }

  subscribeLoanLiquidatedEvent(
    options: EventSubscribeOptions<LendingMarketplaceTypes.LoanLiquidatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LendingMarketplace.contract,
      this,
      options,
      "LoanLiquidated",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | LendingMarketplaceTypes.AdminUpdatedEvent
      | LendingMarketplaceTypes.LoanDetailsEvent
      | LendingMarketplaceTypes.LoanCreatedEvent
      | LendingMarketplaceTypes.LoanCancelledEvent
      | LendingMarketplaceTypes.LoanPaidEvent
      | LendingMarketplaceTypes.LoanAcceptedEvent
      | LendingMarketplaceTypes.LoanLiquidatedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      LendingMarketplace.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    blockTimeStampInSeconds: async (
      params?: LendingMarketplaceTypes.CallMethodParams<"blockTimeStampInSeconds">
    ): Promise<
      LendingMarketplaceTypes.CallMethodResult<"blockTimeStampInSeconds">
    > => {
      return callMethod(
        LendingMarketplace,
        this,
        "blockTimeStampInSeconds",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    calculateInterestPayment: async (
      params: LendingMarketplaceTypes.CallMethodParams<"calculateInterestPayment">
    ): Promise<
      LendingMarketplaceTypes.CallMethodResult<"calculateInterestPayment">
    > => {
      return callMethod(
        LendingMarketplace,
        this,
        "calculateInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateTotalInterestPayment: async (
      params: LendingMarketplaceTypes.CallMethodParams<"calculateTotalInterestPayment">
    ): Promise<
      LendingMarketplaceTypes.CallMethodResult<"calculateTotalInterestPayment">
    > => {
      return callMethod(
        LendingMarketplace,
        this,
        "calculateTotalInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateMarketplaceFee: async (
      params: LendingMarketplaceTypes.CallMethodParams<"calculateMarketplaceFee">
    ): Promise<
      LendingMarketplaceTypes.CallMethodResult<"calculateMarketplaceFee">
    > => {
      return callMethod(
        LendingMarketplace,
        this,
        "calculateMarketplaceFee",
        params,
        getContractByCodeHash
      );
    },
    getAdmin: async (
      params?: LendingMarketplaceTypes.CallMethodParams<"getAdmin">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"getAdmin">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "getAdmin",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalLoans: async (
      params?: LendingMarketplaceTypes.CallMethodParams<"getTotalLoans">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"getTotalLoans">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "getTotalLoans",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getFeeRate: async (
      params?: LendingMarketplaceTypes.CallMethodParams<"getFeeRate">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"getFeeRate">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "getFeeRate",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    createLoan: async (
      params: LendingMarketplaceTypes.CallMethodParams<"createLoan">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"createLoan">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "createLoan",
        params,
        getContractByCodeHash
      );
    },
    borrow: async (
      params: LendingMarketplaceTypes.CallMethodParams<"borrow">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"borrow">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "borrow",
        params,
        getContractByCodeHash
      );
    },
    cancelLoan: async (
      params: LendingMarketplaceTypes.CallMethodParams<"cancelLoan">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"cancelLoan">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "cancelLoan",
        params,
        getContractByCodeHash
      );
    },
    repayLoan: async (
      params: LendingMarketplaceTypes.CallMethodParams<"repayLoan">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"repayLoan">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "repayLoan",
        params,
        getContractByCodeHash
      );
    },
    liquidateLoan: async (
      params: LendingMarketplaceTypes.CallMethodParams<"liquidateLoan">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"liquidateLoan">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "liquidateLoan",
        params,
        getContractByCodeHash
      );
    },
    updateAdmin: async (
      params: LendingMarketplaceTypes.CallMethodParams<"updateAdmin">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"updateAdmin">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "updateAdmin",
        params,
        getContractByCodeHash
      );
    },
    updateFeeRate: async (
      params: LendingMarketplaceTypes.CallMethodParams<"updateFeeRate">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"updateFeeRate">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "updateFeeRate",
        params,
        getContractByCodeHash
      );
    },
    pauseLending: async (
      params?: LendingMarketplaceTypes.CallMethodParams<"pauseLending">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"pauseLending">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "pauseLending",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    enableLending: async (
      params?: LendingMarketplaceTypes.CallMethodParams<"enableLending">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"enableLending">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "enableLending",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: LendingMarketplaceTypes.CallMethodParams<"withdraw">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: LendingMarketplaceTypes.CallMethodParams<"deposit">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    addFeeToken: async (
      params: LendingMarketplaceTypes.CallMethodParams<"addFeeToken">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"addFeeToken">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "addFeeToken",
        params,
        getContractByCodeHash
      );
    },
    removeFeeToken: async (
      params: LendingMarketplaceTypes.CallMethodParams<"removeFeeToken">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"removeFeeToken">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "removeFeeToken",
        params,
        getContractByCodeHash
      );
    },
    isFeeToken: async (
      params: LendingMarketplaceTypes.CallMethodParams<"isFeeToken">
    ): Promise<LendingMarketplaceTypes.CallMethodResult<"isFeeToken">> => {
      return callMethod(
        LendingMarketplace,
        this,
        "isFeeToken",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    blockTimeStampInSeconds: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"blockTimeStampInSeconds">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"blockTimeStampInSeconds">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "blockTimeStampInSeconds",
        params
      );
    },
    calculateInterestPayment: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"calculateInterestPayment">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"calculateInterestPayment">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "calculateInterestPayment",
        params
      );
    },
    calculateTotalInterestPayment: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"calculateTotalInterestPayment">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"calculateTotalInterestPayment">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "calculateTotalInterestPayment",
        params
      );
    },
    calculateMarketplaceFee: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"calculateMarketplaceFee">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"calculateMarketplaceFee">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "calculateMarketplaceFee",
        params
      );
    },
    getAdmin: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"getAdmin">
    ): Promise<LendingMarketplaceTypes.SignExecuteMethodResult<"getAdmin">> => {
      return signExecuteMethod(LendingMarketplace, this, "getAdmin", params);
    },
    getTotalLoans: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"getTotalLoans">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"getTotalLoans">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "getTotalLoans",
        params
      );
    },
    getFeeRate: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"getFeeRate">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"getFeeRate">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "getFeeRate", params);
    },
    createLoan: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"createLoan">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"createLoan">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "createLoan", params);
    },
    borrow: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"borrow">
    ): Promise<LendingMarketplaceTypes.SignExecuteMethodResult<"borrow">> => {
      return signExecuteMethod(LendingMarketplace, this, "borrow", params);
    },
    cancelLoan: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"cancelLoan">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"cancelLoan">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "cancelLoan", params);
    },
    repayLoan: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"repayLoan">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"repayLoan">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "repayLoan", params);
    },
    liquidateLoan: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"liquidateLoan">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"liquidateLoan">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "liquidateLoan",
        params
      );
    },
    updateAdmin: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"updateAdmin">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"updateAdmin">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "updateAdmin", params);
    },
    updateFeeRate: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"updateFeeRate">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"updateFeeRate">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "updateFeeRate",
        params
      );
    },
    pauseLending: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"pauseLending">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"pauseLending">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "pauseLending",
        params
      );
    },
    enableLending: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"enableLending">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"enableLending">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "enableLending",
        params
      );
    },
    withdraw: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<LendingMarketplaceTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(LendingMarketplace, this, "withdraw", params);
    },
    deposit: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"deposit">
    ): Promise<LendingMarketplaceTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(LendingMarketplace, this, "deposit", params);
    },
    addFeeToken: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"addFeeToken">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"addFeeToken">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "addFeeToken", params);
    },
    removeFeeToken: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"removeFeeToken">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"removeFeeToken">
    > => {
      return signExecuteMethod(
        LendingMarketplace,
        this,
        "removeFeeToken",
        params
      );
    },
    isFeeToken: async (
      params: LendingMarketplaceTypes.SignExecuteMethodParams<"isFeeToken">
    ): Promise<
      LendingMarketplaceTypes.SignExecuteMethodResult<"isFeeToken">
    > => {
      return signExecuteMethod(LendingMarketplace, this, "isFeeToken", params);
    },
  };

  async multicall<Calls extends LendingMarketplaceTypes.MultiCallParams>(
    calls: Calls
  ): Promise<LendingMarketplaceTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      LendingMarketplace,
      this,
      calls,
      getContractByCodeHash
    )) as LendingMarketplaceTypes.MultiCallResults<Calls>;
  }
}
