/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as OracleWrapperContractJson } from "../OracleWrapper.ral.json";
import { getContractByCodeHash } from "./contracts";
import { PairInfo, TokenPrice, Value, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace OracleWrapperTypes {
  export type Fields = {
    oracleContractId: HexString;
    heartbeatInterval: bigint;
    upgradeDelay: bigint;
    owner: Address;
    newOwner: Address;
    upgradeInitiated: bigint;
    newCode: HexString;
    newImmFieldsEncoded: HexString;
    newMutFieldsEncoded: HexString;
  };

  export type State = ContractState<Fields>;

  export type ChangeOwnerInitiatedEvent = ContractEvent<{
    owner: Address;
    changeOwner: Address;
  }>;
  export type ChangeOwnerApplyEvent = ContractEvent<{
    owner: Address;
    changeOwner: Address;
  }>;
  export type MigrateInitiatedEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
  }>;
  export type MigrateApplyEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
  }>;
  export type MigrateWithFieldsInitiatedEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
    changeImmFieldsEncoded: HexString;
    changeMutFieldsEncoded: HexString;
  }>;
  export type MigrateWithFieldsApplyEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
    changeImmFieldsEncoded: HexString;
    changeMutFieldsEncoded: HexString;
  }>;
  export type PairAddedEvent = ContractEvent<{
    tokenId: HexString;
    symbol: HexString;
    decimals: bigint;
  }>;

  export interface CallMethodTable {
    changeOwner: {
      params: CallContractParams<{ changeOwner: Address }>;
      result: CallContractResult<null>;
    };
    migrate: {
      params: CallContractParams<{ changeCode: HexString }>;
      result: CallContractResult<null>;
    };
    migrateWithFields: {
      params: CallContractParams<{
        changeCode: HexString;
        changeImmFieldsEncoded: HexString;
        changeMutFieldsEncoded: HexString;
      }>;
      result: CallContractResult<null>;
    };
    changeOwnerApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    migrateApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    migrateWithFieldsApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    resetUpgrade: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getUpgradeDelay: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getNewOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getUpgradeInitiated: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getNewCode: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNewImmFieldsEncoded: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNewMutFieldsEncoded: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    resetFields: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    assertOnlyOwner: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<null>;
    };
    assertUpgradeNotPending: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    assertUpgradeDelayElapsed: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    addPair: {
      params: CallContractParams<{ tokenId: HexString; pairInfo: PairInfo }>;
      result: CallContractResult<null>;
    };
    getPairInfo: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<PairInfo>;
    };
    getTokenPrice: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<TokenPrice>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    changeOwner: {
      params: SignExecuteContractMethodParams<{ changeOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    migrate: {
      params: SignExecuteContractMethodParams<{ changeCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFields: {
      params: SignExecuteContractMethodParams<{
        changeCode: HexString;
        changeImmFieldsEncoded: HexString;
        changeMutFieldsEncoded: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwnerApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrateApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFieldsApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    resetUpgrade: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUpgradeDelay: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUpgradeInitiated: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewCode: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewImmFieldsEncoded: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewMutFieldsEncoded: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    resetFields: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    assertOnlyOwner: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    assertUpgradeNotPending: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    assertUpgradeDelayElapsed: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    addPair: {
      params: SignExecuteContractMethodParams<{
        tokenId: HexString;
        pairInfo: PairInfo;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getPairInfo: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    getTokenPrice: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { pairsByBaseTokenId?: Map<HexString, PairInfo> };
}

class Factory extends ContractFactory<
  OracleWrapperInstance,
  OracleWrapperTypes.Fields
> {
  encodeFields(fields: OracleWrapperTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = {
    ChangeOwnerInitiated: 0,
    ChangeOwnerApply: 1,
    MigrateInitiated: 2,
    MigrateApply: 3,
    MigrateWithFieldsInitiated: 4,
    MigrateWithFieldsApply: 5,
    PairAdded: 6,
  };
  consts = {
    UpgradeErrorCodes: {
      OwnerAllowedOnly: BigInt("13000"),
      UpgradePending: BigInt("13001"),
      UpgradeNotPending: BigInt("13002"),
      UpgradeDelayNotExpired: BigInt("13003"),
      MigrateNotPending: BigInt("13004"),
      MigrateWithFieldsNotPending: BigInt("13005"),
      ChangeOwnerNotPending: BigInt("13006"),
    },
    ErrorCodes: { InvalidTokenId: BigInt("0"), StaleOracle: BigInt("1") },
  };

  at(address: string): OracleWrapperInstance {
    return new OracleWrapperInstance(address);
  }

  tests = {
    changeOwner: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        { changeOwner: Address },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    migrate: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        { changeCode: HexString },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "migrate", params, getContractByCodeHash);
    },
    migrateWithFields: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        {
          changeCode: HexString;
          changeImmFieldsEncoded: HexString;
          changeMutFieldsEncoded: HexString;
        },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
    changeOwnerApply: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "changeOwnerApply",
        params,
        getContractByCodeHash
      );
    },
    migrateApply: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "migrateApply", params, getContractByCodeHash);
    },
    migrateWithFieldsApply: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "migrateWithFieldsApply",
        params,
        getContractByCodeHash
      );
    },
    resetUpgrade: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "resetUpgrade", params, getContractByCodeHash);
    },
    getUpgradeDelay: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "getUpgradeDelay", params, getContractByCodeHash);
    },
    getOwner: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<Address, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "getOwner", params, getContractByCodeHash);
    },
    getNewOwner: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<Address, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "getNewOwner", params, getContractByCodeHash);
    },
    getUpgradeInitiated: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "getUpgradeInitiated",
        params,
        getContractByCodeHash
      );
    },
    getNewCode: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "getNewCode", params, getContractByCodeHash);
    },
    getNewImmFieldsEncoded: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "getNewImmFieldsEncoded",
        params,
        getContractByCodeHash
      );
    },
    getNewMutFieldsEncoded: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "getNewMutFieldsEncoded",
        params,
        getContractByCodeHash
      );
    },
    resetFields: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "resetFields", params, getContractByCodeHash);
    },
    assertOnlyOwner: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        { caller: Address },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "assertOnlyOwner", params, getContractByCodeHash);
    },
    assertUpgradeNotPending: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "assertUpgradeNotPending",
        params,
        getContractByCodeHash
      );
    },
    assertUpgradeDelayElapsed: async (
      params: Omit<
        TestContractParams<
          OracleWrapperTypes.Fields,
          never,
          OracleWrapperTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(
        this,
        "assertUpgradeDelayElapsed",
        params,
        getContractByCodeHash
      );
    },
    addPair: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        { tokenId: HexString; pairInfo: PairInfo },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<null, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "addPair", params, getContractByCodeHash);
    },
    getPairInfo: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        { tokenId: HexString },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<PairInfo, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "getPairInfo", params, getContractByCodeHash);
    },
    getTokenPrice: async (
      params: TestContractParams<
        OracleWrapperTypes.Fields,
        { tokenId: HexString },
        OracleWrapperTypes.Maps
      >
    ): Promise<TestContractResult<TokenPrice, OracleWrapperTypes.Maps>> => {
      return testMethod(this, "getTokenPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: OracleWrapperTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: OracleWrapperTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const OracleWrapper = new Factory(
  Contract.fromJson(
    OracleWrapperContractJson,
    "=78+2=1-1=2-2+5f=2-2+c1=925-1+b=78+7a7e0214696e73657274206174206d617020706174683a2000=356",
    "aa37e72284ced93789d171ae094c9aba37ba6ddb595b1c32ec561ad458433f25",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class OracleWrapperInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    pairsByBaseTokenId: new RalphMap<HexString, PairInfo>(
      OracleWrapper.contract,
      this.contractId,
      "pairsByBaseTokenId"
    ),
  };

  async fetchState(): Promise<OracleWrapperTypes.State> {
    return fetchContractState(OracleWrapper, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeChangeOwnerInitiatedEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.ChangeOwnerInitiatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "ChangeOwnerInitiated",
      fromCount
    );
  }

  subscribeChangeOwnerApplyEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.ChangeOwnerApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "ChangeOwnerApply",
      fromCount
    );
  }

  subscribeMigrateInitiatedEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.MigrateInitiatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "MigrateInitiated",
      fromCount
    );
  }

  subscribeMigrateApplyEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.MigrateApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "MigrateApply",
      fromCount
    );
  }

  subscribeMigrateWithFieldsInitiatedEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.MigrateWithFieldsInitiatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "MigrateWithFieldsInitiated",
      fromCount
    );
  }

  subscribeMigrateWithFieldsApplyEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.MigrateWithFieldsApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "MigrateWithFieldsApply",
      fromCount
    );
  }

  subscribePairAddedEvent(
    options: EventSubscribeOptions<OracleWrapperTypes.PairAddedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OracleWrapper.contract,
      this,
      options,
      "PairAdded",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | OracleWrapperTypes.ChangeOwnerInitiatedEvent
      | OracleWrapperTypes.ChangeOwnerApplyEvent
      | OracleWrapperTypes.MigrateInitiatedEvent
      | OracleWrapperTypes.MigrateApplyEvent
      | OracleWrapperTypes.MigrateWithFieldsInitiatedEvent
      | OracleWrapperTypes.MigrateWithFieldsApplyEvent
      | OracleWrapperTypes.PairAddedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      OracleWrapper.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    changeOwner: async (
      params: OracleWrapperTypes.CallMethodParams<"changeOwner">
    ): Promise<OracleWrapperTypes.CallMethodResult<"changeOwner">> => {
      return callMethod(
        OracleWrapper,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    migrate: async (
      params: OracleWrapperTypes.CallMethodParams<"migrate">
    ): Promise<OracleWrapperTypes.CallMethodResult<"migrate">> => {
      return callMethod(
        OracleWrapper,
        this,
        "migrate",
        params,
        getContractByCodeHash
      );
    },
    migrateWithFields: async (
      params: OracleWrapperTypes.CallMethodParams<"migrateWithFields">
    ): Promise<OracleWrapperTypes.CallMethodResult<"migrateWithFields">> => {
      return callMethod(
        OracleWrapper,
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
    changeOwnerApply: async (
      params?: OracleWrapperTypes.CallMethodParams<"changeOwnerApply">
    ): Promise<OracleWrapperTypes.CallMethodResult<"changeOwnerApply">> => {
      return callMethod(
        OracleWrapper,
        this,
        "changeOwnerApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrateApply: async (
      params?: OracleWrapperTypes.CallMethodParams<"migrateApply">
    ): Promise<OracleWrapperTypes.CallMethodResult<"migrateApply">> => {
      return callMethod(
        OracleWrapper,
        this,
        "migrateApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrateWithFieldsApply: async (
      params?: OracleWrapperTypes.CallMethodParams<"migrateWithFieldsApply">
    ): Promise<
      OracleWrapperTypes.CallMethodResult<"migrateWithFieldsApply">
    > => {
      return callMethod(
        OracleWrapper,
        this,
        "migrateWithFieldsApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    resetUpgrade: async (
      params?: OracleWrapperTypes.CallMethodParams<"resetUpgrade">
    ): Promise<OracleWrapperTypes.CallMethodResult<"resetUpgrade">> => {
      return callMethod(
        OracleWrapper,
        this,
        "resetUpgrade",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUpgradeDelay: async (
      params?: OracleWrapperTypes.CallMethodParams<"getUpgradeDelay">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getUpgradeDelay">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getUpgradeDelay",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOwner: async (
      params?: OracleWrapperTypes.CallMethodParams<"getOwner">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getOwner">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewOwner: async (
      params?: OracleWrapperTypes.CallMethodParams<"getNewOwner">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getNewOwner">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getNewOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUpgradeInitiated: async (
      params?: OracleWrapperTypes.CallMethodParams<"getUpgradeInitiated">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getUpgradeInitiated">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getUpgradeInitiated",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewCode: async (
      params?: OracleWrapperTypes.CallMethodParams<"getNewCode">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getNewCode">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getNewCode",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewImmFieldsEncoded: async (
      params?: OracleWrapperTypes.CallMethodParams<"getNewImmFieldsEncoded">
    ): Promise<
      OracleWrapperTypes.CallMethodResult<"getNewImmFieldsEncoded">
    > => {
      return callMethod(
        OracleWrapper,
        this,
        "getNewImmFieldsEncoded",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewMutFieldsEncoded: async (
      params?: OracleWrapperTypes.CallMethodParams<"getNewMutFieldsEncoded">
    ): Promise<
      OracleWrapperTypes.CallMethodResult<"getNewMutFieldsEncoded">
    > => {
      return callMethod(
        OracleWrapper,
        this,
        "getNewMutFieldsEncoded",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    resetFields: async (
      params?: OracleWrapperTypes.CallMethodParams<"resetFields">
    ): Promise<OracleWrapperTypes.CallMethodResult<"resetFields">> => {
      return callMethod(
        OracleWrapper,
        this,
        "resetFields",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    assertOnlyOwner: async (
      params: OracleWrapperTypes.CallMethodParams<"assertOnlyOwner">
    ): Promise<OracleWrapperTypes.CallMethodResult<"assertOnlyOwner">> => {
      return callMethod(
        OracleWrapper,
        this,
        "assertOnlyOwner",
        params,
        getContractByCodeHash
      );
    },
    assertUpgradeNotPending: async (
      params?: OracleWrapperTypes.CallMethodParams<"assertUpgradeNotPending">
    ): Promise<
      OracleWrapperTypes.CallMethodResult<"assertUpgradeNotPending">
    > => {
      return callMethod(
        OracleWrapper,
        this,
        "assertUpgradeNotPending",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    assertUpgradeDelayElapsed: async (
      params?: OracleWrapperTypes.CallMethodParams<"assertUpgradeDelayElapsed">
    ): Promise<
      OracleWrapperTypes.CallMethodResult<"assertUpgradeDelayElapsed">
    > => {
      return callMethod(
        OracleWrapper,
        this,
        "assertUpgradeDelayElapsed",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    addPair: async (
      params: OracleWrapperTypes.CallMethodParams<"addPair">
    ): Promise<OracleWrapperTypes.CallMethodResult<"addPair">> => {
      return callMethod(
        OracleWrapper,
        this,
        "addPair",
        params,
        getContractByCodeHash
      );
    },
    getPairInfo: async (
      params: OracleWrapperTypes.CallMethodParams<"getPairInfo">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getPairInfo">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getPairInfo",
        params,
        getContractByCodeHash
      );
    },
    getTokenPrice: async (
      params: OracleWrapperTypes.CallMethodParams<"getTokenPrice">
    ): Promise<OracleWrapperTypes.CallMethodResult<"getTokenPrice">> => {
      return callMethod(
        OracleWrapper,
        this,
        "getTokenPrice",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    changeOwner: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"changeOwner">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(OracleWrapper, this, "changeOwner", params);
    },
    migrate: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"migrate">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"migrate">> => {
      return signExecuteMethod(OracleWrapper, this, "migrate", params);
    },
    migrateWithFields: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"migrateWithFields">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"migrateWithFields">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "migrateWithFields",
        params
      );
    },
    changeOwnerApply: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"changeOwnerApply">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"changeOwnerApply">
    > => {
      return signExecuteMethod(OracleWrapper, this, "changeOwnerApply", params);
    },
    migrateApply: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"migrateApply">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"migrateApply">> => {
      return signExecuteMethod(OracleWrapper, this, "migrateApply", params);
    },
    migrateWithFieldsApply: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"migrateWithFieldsApply">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"migrateWithFieldsApply">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "migrateWithFieldsApply",
        params
      );
    },
    resetUpgrade: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"resetUpgrade">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"resetUpgrade">> => {
      return signExecuteMethod(OracleWrapper, this, "resetUpgrade", params);
    },
    getUpgradeDelay: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getUpgradeDelay">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"getUpgradeDelay">
    > => {
      return signExecuteMethod(OracleWrapper, this, "getUpgradeDelay", params);
    },
    getOwner: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getOwner">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"getOwner">> => {
      return signExecuteMethod(OracleWrapper, this, "getOwner", params);
    },
    getNewOwner: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getNewOwner">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"getNewOwner">> => {
      return signExecuteMethod(OracleWrapper, this, "getNewOwner", params);
    },
    getUpgradeInitiated: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getUpgradeInitiated">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"getUpgradeInitiated">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "getUpgradeInitiated",
        params
      );
    },
    getNewCode: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getNewCode">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"getNewCode">> => {
      return signExecuteMethod(OracleWrapper, this, "getNewCode", params);
    },
    getNewImmFieldsEncoded: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getNewImmFieldsEncoded">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"getNewImmFieldsEncoded">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "getNewImmFieldsEncoded",
        params
      );
    },
    getNewMutFieldsEncoded: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getNewMutFieldsEncoded">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"getNewMutFieldsEncoded">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "getNewMutFieldsEncoded",
        params
      );
    },
    resetFields: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"resetFields">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"resetFields">> => {
      return signExecuteMethod(OracleWrapper, this, "resetFields", params);
    },
    assertOnlyOwner: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"assertOnlyOwner">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"assertOnlyOwner">
    > => {
      return signExecuteMethod(OracleWrapper, this, "assertOnlyOwner", params);
    },
    assertUpgradeNotPending: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"assertUpgradeNotPending">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"assertUpgradeNotPending">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "assertUpgradeNotPending",
        params
      );
    },
    assertUpgradeDelayElapsed: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"assertUpgradeDelayElapsed">
    ): Promise<
      OracleWrapperTypes.SignExecuteMethodResult<"assertUpgradeDelayElapsed">
    > => {
      return signExecuteMethod(
        OracleWrapper,
        this,
        "assertUpgradeDelayElapsed",
        params
      );
    },
    addPair: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"addPair">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"addPair">> => {
      return signExecuteMethod(OracleWrapper, this, "addPair", params);
    },
    getPairInfo: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getPairInfo">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"getPairInfo">> => {
      return signExecuteMethod(OracleWrapper, this, "getPairInfo", params);
    },
    getTokenPrice: async (
      params: OracleWrapperTypes.SignExecuteMethodParams<"getTokenPrice">
    ): Promise<OracleWrapperTypes.SignExecuteMethodResult<"getTokenPrice">> => {
      return signExecuteMethod(OracleWrapper, this, "getTokenPrice", params);
    },
  };

  async multicall<Callss extends OracleWrapperTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<OracleWrapperTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      OracleWrapper,
      this,
      callss,
      getContractByCodeHash
    )) as OracleWrapperTypes.MulticallReturnType<Callss>;
  }
}
