/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as AddFeeTokenScriptJson } from "../scripts/AddFeeToken.ral.json";
import { default as BorrowScriptJson } from "../scripts/Borrow.ral.json";
import { default as CancelLoanScriptJson } from "../scripts/CancelLoan.ral.json";
import { default as ClaimCollateralScriptJson } from "../scripts/ClaimCollateral.ral.json";
import { default as CreateLoanScriptJson } from "../scripts/CreateLoan.ral.json";
import { default as GetTokenScriptJson } from "../test/GetToken.ral.json";
import { default as IUpgradableChangeOwnerApplyTXScriptJson } from "../lib/IUpgradableChangeOwnerApplyTX.ral.json";
import { default as IUpgradableChangeOwnerTXScriptJson } from "../lib/IUpgradableChangeOwnerTX.ral.json";
import { default as IUpgradableMigrateApplyTXScriptJson } from "../lib/IUpgradableMigrateApplyTX.ral.json";
import { default as IUpgradableMigrateTXScriptJson } from "../lib/IUpgradableMigrateTX.ral.json";
import { default as IUpgradableMigrateWithFieldsApplyTXScriptJson } from "../lib/IUpgradableMigrateWithFieldsApplyTX.ral.json";
import { default as IUpgradableMigrateWithFieldsTXScriptJson } from "../lib/IUpgradableMigrateWithFieldsTX.ral.json";
import { default as IUpgradableResetUpgradeTXScriptJson } from "../lib/IUpgradableResetUpgradeTX.ral.json";
import { default as LiquidateLoanScriptJson } from "../scripts/LiquidateLoan.ral.json";
import { default as RemoveFeeTokenScriptJson } from "../scripts/RemoveFeeToken.ral.json";
import { default as RepayLoanScriptJson } from "../scripts/RepayLoan.ral.json";
import { PairInfo, TokenPrice, Value, AllStructs } from "./types";

export const AddFeeToken = new ExecutableScript<{
  marketplace: HexString;
  tokenId: HexString;
}>(
  Script.fromJson(AddFeeTokenScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const Borrow = new ExecutableScript<{
  loanId: HexString;
  lendingMarketplace: HexString;
}>(Script.fromJson(BorrowScriptJson, "", AllStructs), getContractByCodeHash);

export const CancelLoan = new ExecutableScript<{
  marketplace: HexString;
  loanId: HexString;
}>(
  Script.fromJson(CancelLoanScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const ClaimCollateral = new ExecutableScript<{
  marketplace: HexString;
  loanId: HexString;
}>(
  Script.fromJson(ClaimCollateralScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const CreateLoan = new ExecutableScript<{
  lendingTokenId: HexString;
  collateralTokenId: HexString;
  lendingAmount: bigint;
  collateralAmount: bigint;
  interestRate: bigint;
  duration: bigint;
  canBeLiquidated: boolean;
  marketplace: HexString;
}>(
  Script.fromJson(CreateLoanScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const GetToken = new ExecutableScript<{
  token: HexString;
  sender: Address;
  amount: bigint;
}>(Script.fromJson(GetTokenScriptJson, "", AllStructs), getContractByCodeHash);

export const IUpgradableChangeOwnerApplyTX = new ExecutableScript<{
  upgradable: HexString;
}>(
  Script.fromJson(IUpgradableChangeOwnerApplyTXScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const IUpgradableChangeOwnerTX = new ExecutableScript<{
  upgradable: HexString;
  changeOwner: Address;
}>(
  Script.fromJson(IUpgradableChangeOwnerTXScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const IUpgradableMigrateApplyTX = new ExecutableScript<{
  upgradable: HexString;
}>(
  Script.fromJson(IUpgradableMigrateApplyTXScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const IUpgradableMigrateTX = new ExecutableScript<{
  upgradable: HexString;
  changeCode: HexString;
}>(
  Script.fromJson(IUpgradableMigrateTXScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const IUpgradableMigrateWithFieldsApplyTX = new ExecutableScript<{
  upgradable: HexString;
}>(
  Script.fromJson(
    IUpgradableMigrateWithFieldsApplyTXScriptJson,
    "",
    AllStructs
  ),
  getContractByCodeHash
);

export const IUpgradableMigrateWithFieldsTX = new ExecutableScript<{
  upgradable: HexString;
  changeCode: HexString;
  changeImmFieldsEncoded: HexString;
  changeMutFieldsEncoded: HexString;
}>(
  Script.fromJson(IUpgradableMigrateWithFieldsTXScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const IUpgradableResetUpgradeTX = new ExecutableScript<{
  upgradable: HexString;
}>(
  Script.fromJson(IUpgradableResetUpgradeTXScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const LiquidateLoan = new ExecutableScript<{
  marketplace: HexString;
  loanId: HexString;
  amount: bigint;
}>(
  Script.fromJson(LiquidateLoanScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const RemoveFeeToken = new ExecutableScript<{
  marketplace: HexString;
  tokenId: HexString;
}>(
  Script.fromJson(RemoveFeeTokenScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const RepayLoan = new ExecutableScript<{
  marketplace: HexString;
  loanId: HexString;
  borrowedTokenId: HexString;
  amount: bigint;
}>(Script.fromJson(RepayLoanScriptJson, "", AllStructs), getContractByCodeHash);
