/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TestOracleContractJson } from "../test/TestOracle.ral.json";
import { getContractByCodeHash } from "./contracts";
import { PairInfo, TokenPrice, Value, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace TestOracleTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    getValue: {
      params: CallContractParams<{ pair: HexString }>;
      result: CallContractResult<[bigint, bigint]>;
    };
    setPrice: {
      params: CallContractParams<{
        pair: HexString;
        price: bigint;
        timestamp: bigint;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getValue: {
      params: SignExecuteContractMethodParams<{ pair: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    setPrice: {
      params: SignExecuteContractMethodParams<{
        pair: HexString;
        price: bigint;
        timestamp: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { pricesByPair?: Map<HexString, Value> };
}

class Factory extends ContractFactory<TestOracleInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): TestOracleInstance {
    return new TestOracleInstance(address);
  }

  tests = {
    getValue: async (
      params: Omit<
        TestContractParams<never, { pair: HexString }, TestOracleTypes.Maps>,
        "initialFields"
      >
    ): Promise<TestContractResult<[bigint, bigint], TestOracleTypes.Maps>> => {
      return testMethod(this, "getValue", params, getContractByCodeHash);
    },
    setPrice: async (
      params: Omit<
        TestContractParams<
          never,
          { pair: HexString; price: bigint; timestamp: bigint },
          TestOracleTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<null, TestOracleTypes.Maps>> => {
      return testMethod(this, "setPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: {},
    asset?: Asset,
    address?: string,
    maps?: TestOracleTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const TestOracle = new Factory(
  Contract.fromJson(
    TestOracleContractJson,
    "=10-2+b5=119-1+d=47-1+a=36+7a7e021472656d6f7665206174206d617020706174683a2000=42+7a7e0214696e73657274206174206d617020706174683a2000=16",
    "885b553e5c96b504e524aca9020c00544a2f5fef4134b0ab6e11504e11ee4485",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class TestOracleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    pricesByPair: new RalphMap<HexString, Value>(
      TestOracle.contract,
      this.contractId,
      "pricesByPair"
    ),
  };

  async fetchState(): Promise<TestOracleTypes.State> {
    return fetchContractState(TestOracle, this);
  }

  view = {
    getValue: async (
      params: TestOracleTypes.CallMethodParams<"getValue">
    ): Promise<TestOracleTypes.CallMethodResult<"getValue">> => {
      return callMethod(
        TestOracle,
        this,
        "getValue",
        params,
        getContractByCodeHash
      );
    },
    setPrice: async (
      params: TestOracleTypes.CallMethodParams<"setPrice">
    ): Promise<TestOracleTypes.CallMethodResult<"setPrice">> => {
      return callMethod(
        TestOracle,
        this,
        "setPrice",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getValue: async (
      params: TestOracleTypes.SignExecuteMethodParams<"getValue">
    ): Promise<TestOracleTypes.SignExecuteMethodResult<"getValue">> => {
      return signExecuteMethod(TestOracle, this, "getValue", params);
    },
    setPrice: async (
      params: TestOracleTypes.SignExecuteMethodParams<"setPrice">
    ): Promise<TestOracleTypes.SignExecuteMethodResult<"setPrice">> => {
      return signExecuteMethod(TestOracle, this, "setPrice", params);
    },
  };

  async multicall<Callss extends TestOracleTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<TestOracleTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      TestOracle,
      this,
      callss,
      getContractByCodeHash
    )) as TestOracleTypes.MulticallReturnType<Callss>;
  }
}
