/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TestLendingMarketplaceUtilsContractJson } from "../test/TestLendingMarketplaceUtils.ral.json";
import { getContractByCodeHash } from "./contracts";
import { PairInfo, TokenPrice, Value, AllStructs } from "./types";

// Custom types for the contract
export namespace TestLendingMarketplaceUtilsTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    blockTimeStampInSeconds: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    calculateInterestPayment: {
      params: CallContractParams<{
        currentBlockTimeStamp: bigint;
        loanTimestamp: bigint;
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    calculateTotalInterestPayment: {
      params: CallContractParams<{
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    calculateMarketplaceFee: {
      params: CallContractParams<{ amount: bigint; feeRate: bigint }>;
      result: CallContractResult<bigint>;
    };
    normalizeAmount: {
      params: CallContractParams<{ amount: bigint; decimals: bigint }>;
      result: CallContractResult<bigint>;
    };
    calculateLTV: {
      params: CallContractParams<{
        collateralTokenAmount: bigint;
        collateralTokenPrice: TokenPrice;
        borrowedTokenAmount: bigint;
        borrowedTokenPrice: TokenPrice;
      }>;
      result: CallContractResult<bigint>;
    };
    calculateLiquidationAmount: {
      params: CallContractParams<{
        collateralValue: bigint;
        loanValue: bigint;
        fee: bigint;
        ltvTarget: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    blockTimeStampInSeconds: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    calculateInterestPayment: {
      params: SignExecuteContractMethodParams<{
        currentBlockTimeStamp: bigint;
        loanTimestamp: bigint;
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateTotalInterestPayment: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        interest: bigint;
        days: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateMarketplaceFee: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        feeRate: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    normalizeAmount: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        decimals: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateLTV: {
      params: SignExecuteContractMethodParams<{
        collateralTokenAmount: bigint;
        collateralTokenPrice: TokenPrice;
        borrowedTokenAmount: bigint;
        borrowedTokenPrice: TokenPrice;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateLiquidationAmount: {
      params: SignExecuteContractMethodParams<{
        collateralValue: bigint;
        loanValue: bigint;
        fee: bigint;
        ltvTarget: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TestLendingMarketplaceUtilsInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  consts = { Day: BigInt("86400") };

  at(address: string): TestLendingMarketplaceUtilsInstance {
    return new TestLendingMarketplaceUtilsInstance(address);
  }

  tests = {
    blockTimeStampInSeconds: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "testArgs" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "blockTimeStampInSeconds",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    calculateInterestPayment: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          {
            currentBlockTimeStamp: bigint;
            loanTimestamp: bigint;
            amount: bigint;
            interest: bigint;
            days: bigint;
          }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateTotalInterestPayment: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { amount: bigint; interest: bigint; days: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateTotalInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateMarketplaceFee: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { amount: bigint; feeRate: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateMarketplaceFee",
        params,
        getContractByCodeHash
      );
    },
    normalizeAmount: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { amount: bigint; decimals: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "normalizeAmount", params, getContractByCodeHash);
    },
    calculateLTV: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          {
            collateralTokenAmount: bigint;
            collateralTokenPrice: TokenPrice;
            borrowedTokenAmount: bigint;
            borrowedTokenPrice: TokenPrice;
          }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "calculateLTV", params, getContractByCodeHash);
    },
    calculateLiquidationAmount: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          {
            collateralValue: bigint;
            loanValue: bigint;
            fee: bigint;
            ltvTarget: bigint;
          }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateLiquidationAmount",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TestLendingMarketplaceUtils = new Factory(
  Contract.fromJson(
    TestLendingMarketplaceUtilsContractJson,
    "",
    "1360c78144d45f2f2ff10abfa7d9c5b85586004233f1d67dbc03415d6462ce69",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class TestLendingMarketplaceUtilsInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TestLendingMarketplaceUtilsTypes.State> {
    return fetchContractState(TestLendingMarketplaceUtils, this);
  }

  view = {
    blockTimeStampInSeconds: async (
      params?: TestLendingMarketplaceUtilsTypes.CallMethodParams<"blockTimeStampInSeconds">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"blockTimeStampInSeconds">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "blockTimeStampInSeconds",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    calculateInterestPayment: async (
      params: TestLendingMarketplaceUtilsTypes.CallMethodParams<"calculateInterestPayment">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"calculateInterestPayment">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateTotalInterestPayment: async (
      params: TestLendingMarketplaceUtilsTypes.CallMethodParams<"calculateTotalInterestPayment">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"calculateTotalInterestPayment">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateTotalInterestPayment",
        params,
        getContractByCodeHash
      );
    },
    calculateMarketplaceFee: async (
      params: TestLendingMarketplaceUtilsTypes.CallMethodParams<"calculateMarketplaceFee">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"calculateMarketplaceFee">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateMarketplaceFee",
        params,
        getContractByCodeHash
      );
    },
    normalizeAmount: async (
      params: TestLendingMarketplaceUtilsTypes.CallMethodParams<"normalizeAmount">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"normalizeAmount">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "normalizeAmount",
        params,
        getContractByCodeHash
      );
    },
    calculateLTV: async (
      params: TestLendingMarketplaceUtilsTypes.CallMethodParams<"calculateLTV">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"calculateLTV">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateLTV",
        params,
        getContractByCodeHash
      );
    },
    calculateLiquidationAmount: async (
      params: TestLendingMarketplaceUtilsTypes.CallMethodParams<"calculateLiquidationAmount">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.CallMethodResult<"calculateLiquidationAmount">
    > => {
      return callMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateLiquidationAmount",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    blockTimeStampInSeconds: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"blockTimeStampInSeconds">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"blockTimeStampInSeconds">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "blockTimeStampInSeconds",
        params
      );
    },
    calculateInterestPayment: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"calculateInterestPayment">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"calculateInterestPayment">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateInterestPayment",
        params
      );
    },
    calculateTotalInterestPayment: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"calculateTotalInterestPayment">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"calculateTotalInterestPayment">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateTotalInterestPayment",
        params
      );
    },
    calculateMarketplaceFee: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"calculateMarketplaceFee">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"calculateMarketplaceFee">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateMarketplaceFee",
        params
      );
    },
    normalizeAmount: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"normalizeAmount">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"normalizeAmount">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "normalizeAmount",
        params
      );
    },
    calculateLTV: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"calculateLTV">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"calculateLTV">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateLTV",
        params
      );
    },
    calculateLiquidationAmount: async (
      params: TestLendingMarketplaceUtilsTypes.SignExecuteMethodParams<"calculateLiquidationAmount">
    ): Promise<
      TestLendingMarketplaceUtilsTypes.SignExecuteMethodResult<"calculateLiquidationAmount">
    > => {
      return signExecuteMethod(
        TestLendingMarketplaceUtils,
        this,
        "calculateLiquidationAmount",
        params
      );
    },
  };

  async multicall<
    Callss extends TestLendingMarketplaceUtilsTypes.MultiCallParams[]
  >(
    ...callss: Callss
  ): Promise<TestLendingMarketplaceUtilsTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      TestLendingMarketplaceUtils,
      this,
      callss,
      getContractByCodeHash
    )) as TestLendingMarketplaceUtilsTypes.MulticallReturnType<Callss>;
  }
}
