/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct } from "@alephium/web3";
import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));
export interface PairInfo extends Record<string, Val> {
  symbol: HexString;
  decimals: bigint;
}
export interface TokenPrice extends Record<string, Val> {
  price: bigint;
  timestamp: bigint;
  decimals: bigint;
}
export interface Value extends Record<string, Val> {
  price: bigint;
  timestamp: bigint;
}
